"""empty message

Revision ID: 2f08f1e6e15f
Revises: 9c5707e7dde3
Create Date: 2020-10-08 01:16:42.216504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f08f1e6e15f'
down_revision = '9c5707e7dde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stickies', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stickies', 'username')
    # ### end Alembic commands ###
