"""empty message

Revision ID: 498244308191
Revises: 856cac3e13a8
Create Date: 2020-10-06 01:40:06.098339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498244308191'
down_revision = '856cac3e13a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
