"""empty message

Revision ID: 568d01941150
Revises: 498244308191
Create Date: 2020-10-06 01:58:22.197864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568d01941150'
down_revision = '498244308191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('github_access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
